### ISSUE TITLE
Add USB support

### ISSUE THREAD

**Issue by abo-github** [unosquare/sparkfunfingerprint#4]
Right at the moment, only COM ports can be selected.
But if you solder a USB cabel to the pads, you can use the module via USB.
The fingerprint sensor is than recognized as a CD drive (but without a CD)

Running the SDK Demo application (https://cdn.sparkfun.com/assets/learn_tutorials/7/2/3/20171129-SDK_Demo_Ver1.9.zip) there is the option to select the USB port - and it works like a charm!

**Comment by k3z0** [comment]
Hi @abo-github, we are going to review this functionality in the next release. Maybe we could use a library like [LibUsbDotNet](https://github.com/LibUsbDotNet/LibUsbDotNet) for achieve an OS and driver independent implementation.

Thanks for your suggestion.

**Comment by ArturKarbone** [comment]
@k3z0 my understanding is that USB feature has not been implemented? Any plans on this?
