### ISSUE TITLE
Problem to get image from reader

### ISSUE THREAD

**Issue by dgsoftlabs** [unosquare/sparkfunfingerprint#6]
Hi,
At the beginning I would like to thanks for great project its very helpful.

I got problem with two functionality:
1. GetRawImageAsync()
2. GetImageAsync()

After invoking GetFingerprintImageResponse.Image is empty the same GetRawImageResponse.Image.
Image = 'res.Image' threw an exception of type 'System.NullReferenceException'
Can you help me with that ? Maybe code is wrong ?

I'm use WPF and programing on Windows

Code:
GetRawImageResponse res =   await reader.GetRawImageAsync(token);
byte[] imng = res. Image;
 
Thanks

**Comment by k3z0** [comment]
Hi @DanielSan1000 

It seems like the problem was caused by a timeout, because the amount of data the sensor needs to transfer.

We just release a new nuget (1.2.0) that solves this problem. Could you please give it a try and let us know if the blomen was solved.

Thanks.

**Comment by dgsoftlabs** [comment]
Hi,

I tired new version and bytes are loaded from device. Its look that working properly.
Now I'm trying to convert it into bitmap or image. Not that easy.

Thanks for help.

**Comment by dgsoftlabs** [comment]
I figure out how convert it. everything work properly.
Thanks

**Comment by k3z0** [comment]
Hi @DanielSan1000 

I added and example in the Playground Project for converting the raw image bytes into a bmp image ([here](https://github.com/unosquare/sparkfunfingerprint/blob/1462445daa06f708b8173c8265d5b0e92cbbd505/src/Unosquare.Sparkfun.Playground/Program.cs#L145)).
